package com.bizarreelectronics.crm.lint

import com.android.tools.lint.client.api.UElementHandler
import com.android.tools.lint.detector.api.Category
import com.android.tools.lint.detector.api.Detector
import com.android.tools.lint.detector.api.Implementation
import com.android.tools.lint.detector.api.Issue
import com.android.tools.lint.detector.api.JavaContext
import com.android.tools.lint.detector.api.Scope
import com.android.tools.lint.detector.api.Severity
import org.jetbrains.uast.UClass
import org.jetbrains.uast.UElement
import org.jetbrains.uast.UField

/**
 * Detects Kotlin `object` declarations that hold `var` (mutable) fields.
 *
 * # Why this rule exists
 *
 * A Kotlin `object` is a JVM-level singleton — it lives for the lifetime of
 * the process. Mutable state inside an `object` is therefore effectively global
 * state. This causes two classes of bugs in an Android + Hilt project:
 *
 * 1. **Test isolation failures** — the singleton persists across test cases even
 *    when the Activity / Fragment lifecycle is torn down, so one test's mutations
 *    silently pollute the next.
 * 2. **DI bypass** — state held in `object` is invisible to Hilt's scope graph,
 *    making it impossible to replace with test doubles or to reason about which
 *    component owns the data.
 *
 * # Recommended fix
 *
 * Move the state into a Hilt-provided `@Singleton`-scoped class and inject it
 * wherever needed. The DI graph controls lifetime, making replacement in tests
 * trivial via `@TestInstallIn`.
 *
 * # Suppression
 *
 * In the rare case that a stateful singleton is intentional (e.g. a performance
 * cache that is explicitly cleared in tests), suppress with:
 * ```kotlin
 * @SuppressLint("StatefulObjectSingleton")
 * object MyCache { var data: Map<String, Any> = emptyMap() }
 * ```
 */
class StatefulObjectSingletonDetector : Detector(), Detector.UastScanner {

    companion object {
        val ISSUE: Issue = Issue.create(
            id = "StatefulObjectSingleton",
            briefDescription = "Mutable state in a Kotlin `object` singleton",
            explanation = """
                A Kotlin `object` is a JVM singleton that lives for the process lifetime. \
                Mutable `var` fields inside an `object` are global state, which causes \
                test-isolation failures and bypasses the Hilt dependency-injection graph.

                Use Hilt-provided singletons instead:
                ```kotlin
                @Singleton
                class MyRepository @Inject constructor(...) {
                    var data: ...  // scoped, replaceable in tests
                }
                ```

                Suppress with `@SuppressLint("StatefulObjectSingleton")` only when the \
                statefulness is intentional and the object is explicitly reset between tests.
            """,
            category = Category.CORRECTNESS,
            priority = 8,
            severity = Severity.ERROR,
            implementation = Implementation(
                StatefulObjectSingletonDetector::class.java,
                Scope.JAVA_FILE_SCOPE,
            ),
        )

        /** Packages that are allowed to contain stateful objects (DI / generated code). */
        private val ALLOWED_PACKAGE_SEGMENTS = setOf(".di.", "androidx.", "dagger.")

        /** Class-name prefixes generated by Dagger/Hilt code generation. */
        private val GENERATED_NAME_PREFIXES = setOf("Dagger_", "Hilt_", "DaggerHilt")
    }

    override fun getApplicableUastTypes(): List<Class<out UElement>> =
        listOf(UClass::class.java)

    override fun createUastHandler(context: JavaContext): UElementHandler =
        object : UElementHandler() {
            override fun visitClass(node: UClass) {
                // Only flag Kotlin companion-less objects (isObject == true in UAST).
                // UClass.isObject is true when the Kotlin source uses `object Foo`.
                if (!node.isObject()) return

                val qualifiedName = node.qualifiedName ?: return

                // Skip well-known safe packages.
                if (ALLOWED_PACKAGE_SEGMENTS.any { qualifiedName.contains(it) }) return
                if (qualifiedName.startsWith("androidx.")) return

                // Skip Dagger/Hilt generated class names.
                val simpleName = node.name ?: return
                if (GENERATED_NAME_PREFIXES.any { simpleName.startsWith(it) }) return

                // Inspect each field for mutability.
                for (field in node.fields) {
                    if (isMutableField(field)) {
                        context.report(
                            issue = ISSUE,
                            location = context.getNameLocation(field),
                            message = "Mutable `var` field `${field.name}` in singleton `object ${node.name}`. " +
                                "Use Hilt-provided singletons; top-level `object` with mutable state leaks across tests.",
                        )
                    }
                }
            }
        }

    /**
     * Returns true if the UAST field represents a Kotlin `var` (i.e. has a setter
     * and is not marked as `@JvmField val` or similar immutable pattern).
     */
    private fun isMutableField(field: UField): Boolean {
        // Kotlin `var` fields compile to a field + a non-private setter.
        // We check the source PSI element for the var keyword when available;
        // otherwise fall back to checking setter visibility via the backing element.
        val sourcePsi = field.sourcePsi
        if (sourcePsi != null) {
            val text = sourcePsi.text
            // Heuristic: the PSI text of a `var` property starts with "var "
            // or contains " var " after modifiers.
            if (Regex("""(?:^|\s)var\s""").containsMatchIn(text)) return true
        }
        // Secondary check: field is not final (covers Java-style interop).
        return !field.isFinal
    }

    /** Extension to check whether a UClass represents a Kotlin singleton object. */
    private fun UClass.isObject(): Boolean {
        // Kotlin objects produce a class with a public static INSTANCE field named "INSTANCE"
        // and a private constructor. The most reliable check via UAST is inspecting the
        // underlying sourcePsi for the `object` keyword.
        val psi = sourcePsi ?: return false
        return psi.text.trimStart().let {
            it.startsWith("object ") ||
                Regex("""(?:^|\n)\s*(?:(?:internal|private|protected|public|abstract|open|sealed)\s+)*object\s""")
                    .containsMatchIn(it)
        }
    }
}
