import Foundation
import Core
import Networking

// MARK: - §6.13 Auto PO Generator

/// Converts reorder suggestions into draft PurchaseOrders via the existing PO pipeline.
/// Depends on `PurchaseOrderRepository` (§58).
@MainActor
public final class AutoPOGenerator {

    public enum GenerationResult: Sendable {
        case created(PurchaseOrder)
        case failed(String)
    }

    @ObservationIgnored private let poRepo: PurchaseOrderRepository
    @ObservationIgnored private let api: APIClient

    public init(api: APIClient) {
        self.api = api
        self.poRepo = LivePurchaseOrderRepository(api: api)
    }

    // MARK: - Generate

    /// Creates one draft PurchaseOrder from all suggestions (grouped by optional supplier).
    /// - Parameters:
    ///   - suggestions: Engine output.
    ///   - supplierId: Target supplier; uses first available if nil.
    ///   - policy: The policy used to generate these suggestions (stored in PO notes).
    public func generateDraftPO(
        from suggestions: [ReorderEngineSuggestion],
        supplierId: Int64,
        policy: ReorderPolicy
    ) async -> GenerationResult {
        guard !suggestions.isEmpty else {
            return .failed("No suggestions provided.")
        }

        let lines = suggestions.map { s in
            POLineItemRequest(
                sku: s.item.sku ?? s.item.displayName,
                name: s.item.displayName,
                qtyOrdered: s.suggestedQty,
                unitCostCents: s.item.priceCents ?? 0
            )
        }

        let notesLines = [
            "Auto-generated by ReorderSuggestionEngine.",
            "Policy: lead-time \(policy.leadTimeDays)d, safety \(policy.safetyStock), min-order \(policy.minOrderQty).",
            "\(suggestions.count) SKU(s) below reorder threshold."
        ]

        let request = CreatePurchaseOrderRequest(
            supplierId: supplierId,
            expectedDate: Calendar.current.date(byAdding: .day, value: policy.leadTimeDays, to: Date()),
            items: lines,
            notes: notesLines.joined(separator: " ")
        )

        do {
            let po = try await poRepo.create(request)
            AppLog.ui.info("AutoPOGenerator: Draft PO #\(po.id, privacy: .public) created with \(lines.count, privacy: .public) lines.")
            return .created(po)
        } catch {
            AppLog.ui.error("AutoPOGenerator: PO creation failed — \(error.localizedDescription, privacy: .public)")
            return .failed(error.localizedDescription)
        }
    }
}
