import Foundation

// §4.3 — Full-fidelity ticket create with idempotency key + source-ticket linking.
//
// Server: POST /api/v1/tickets
// The basic `CreateTicketRequest` in CreateEndpoints.swift is the minimal shape.
// This file adds:
//   • `idempotency_key`  — UUID sent in request body (per §4.3 spec).
//   • `source_ticket_id` — links to the estimate/ticket being converted from.
//   • `service_type`     — walk-in / mail-in / on-site / pick-up / drop-off.
//   • `tags`             — array of label strings.
//   • `how_did_u_find_us` / `referral_source` — source / referral fields.
//   • `due_on`           — ISO-8601 date string (YYYY-MM-DD).
//   • `deposit`          — optional deposit amount collected.
//
// The `createTicketFull` overload sends the `Idempotency-Key` HTTP header in
// addition to embedding the key in the body so the server can deduplicate on
// either surface.

// MARK: - Service types

/// §4.3 — Ticket service-type values as loaded from `GET /settings/store`.
/// The raw values match server expectations. The list is user-customisable but
/// these five are the out-of-box defaults (§4.3 note about rethinking types).
public enum TicketServiceType: String, CaseIterable, Sendable, Codable {
    case walkIn   = "walk_in"
    case mailIn   = "mail_in"
    case onSite   = "on_site"
    case pickUp   = "pick_up"
    case dropOff  = "drop_off"

    public var displayName: String {
        switch self {
        case .walkIn:  return "Walk-in"
        case .mailIn:  return "Mail-in"
        case .onSite:  return "On-site"
        case .pickUp:  return "Pick-up"
        case .dropOff: return "Drop-off"
        }
    }
}

// MARK: - Full create request

/// Full-fidelity ticket create request.
/// Sent as `POST /api/v1/tickets`.
/// The `idempotencyKey` is embedded in the body AND sent as an HTTP header so
/// the server can deduplicate via either mechanism.
public struct CreateTicketFullRequest: Encodable, Sendable {
    public let customerId: Int64
    public let devices: [CreateTicketRequest.NewDevice]
    public let statusId: Int64?
    public let assignedTo: Int64?
    public let serviceType: String?
    public let tags: [String]?
    public let howDidUFindUs: String?
    public let referralSource: String?
    public let dueOn: String?
    /// Optional deposit amount in dollars (not cents).
    public let deposit: Double?
    /// UUID generated by the client — embeds into body for deduplication.
    public let idempotencyKey: String?
    /// Source ticket / estimate id when converting (links lineage).
    public let sourceTicketId: Int64?

    public init(
        customerId: Int64,
        devices: [CreateTicketRequest.NewDevice],
        statusId: Int64? = nil,
        assignedTo: Int64? = nil,
        serviceType: String? = nil,
        tags: [String]? = nil,
        howDidUFindUs: String? = nil,
        referralSource: String? = nil,
        dueOn: String? = nil,
        deposit: Double? = nil,
        idempotencyKey: String? = nil,
        sourceTicketId: Int64? = nil
    ) {
        self.customerId = customerId
        self.devices = devices
        self.statusId = statusId
        self.assignedTo = assignedTo
        self.serviceType = serviceType
        self.tags = tags
        self.howDidUFindUs = howDidUFindUs
        self.referralSource = referralSource
        self.dueOn = dueOn
        self.deposit = deposit
        self.idempotencyKey = idempotencyKey
        self.sourceTicketId = sourceTicketId
    }

    enum CodingKeys: String, CodingKey {
        case devices
        case customerId      = "customer_id"
        case statusId        = "status_id"
        case assignedTo      = "assigned_to"
        case serviceType     = "service_type"
        case tags
        case howDidUFindUs   = "how_did_u_find_us"
        case referralSource  = "referral_source"
        case dueOn           = "due_on"
        case deposit
        case idempotencyKey  = "idempotency_key"
        case sourceTicketId  = "source_ticket_id"
    }
}

// MARK: - APIClient wrapper

public extension APIClient {
    /// `POST /api/v1/tickets` — full-fidelity create.
    ///
    /// The `idempotencyKey` is embedded in the request body as `idempotency_key`.
    /// On retry with the same key the server returns the already-created ticket's
    /// `id` without creating a duplicate.
    func createTicketFull(_ req: CreateTicketFullRequest) async throws -> CreatedResource {
        try await post("/api/v1/tickets", body: req, as: CreatedResource.self)
    }
}
