import SwiftUI
import Charts
import DesignSystem

// MARK: - §15.2 Cohort Revenue Retention Card
//
// Shows what percentage of customers from a given acquisition cohort returned
// and generated revenue in subsequent months.
//
// Endpoint: GET /api/v1/reports/cohort-retention?from_date=&to_date=
// Server shape:
//   { cohorts: [{ cohortMonth: String, rows: [{ monthOffset: Int, retentionPct: Double, revenueDollars: Double }] }] }
//
// iPhone: scrollable heatmap grid (cohortMonth rows × monthOffset columns).
// iPad: same grid with wider cells + value overlay.

// MARK: - Models

public struct CohortRetentionData: Decodable, Sendable {
    public let cohorts: [CohortRow]

    public init(cohorts: [CohortRow]) { self.cohorts = cohorts }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.cohorts = (try? c.decode([CohortRow].self, forKey: .cohorts)) ?? []
    }
    enum CodingKeys: String, CodingKey { case cohorts }
}

public struct CohortRow: Decodable, Sendable, Identifiable {
    public let id: String
    /// e.g. "2024-01"
    public let cohortMonth: String
    public let cells: [CohortCell]

    public init(cohortMonth: String, cells: [CohortCell]) {
        self.id = cohortMonth
        self.cohortMonth = cohortMonth
        self.cells = cells
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.cohortMonth = (try? c.decode(String.self, forKey: .cohortMonth)) ?? ""
        self.id = cohortMonth
        self.cells = (try? c.decode([CohortCell].self, forKey: .rows)) ?? []
    }

    enum CodingKeys: String, CodingKey {
        case cohortMonth = "cohort_month"
        case rows
    }
}

public struct CohortCell: Decodable, Sendable, Identifiable {
    public var id: String { "\(monthOffset)" }
    /// 0 = acquisition month, 1 = one month later, etc.
    public let monthOffset: Int
    /// % of original cohort customers who returned this month.
    public let retentionPct: Double
    /// Revenue generated by this cohort in this month.
    public let revenueDollars: Double

    public init(monthOffset: Int, retentionPct: Double, revenueDollars: Double) {
        self.monthOffset = monthOffset
        self.retentionPct = retentionPct
        self.revenueDollars = revenueDollars
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.monthOffset = (try? c.decode(Int.self, forKey: .monthOffset)) ?? 0
        self.retentionPct = (try? c.decode(Double.self, forKey: .retentionPct)) ?? 0
        self.revenueDollars = (try? c.decode(Double.self, forKey: .revenueDollars)) ?? 0
    }

    enum CodingKeys: String, CodingKey {
        case monthOffset   = "month_offset"
        case retentionPct  = "retention_pct"
        case revenueDollars = "revenue"
    }
}

// MARK: - Card View

public struct CohortRetentionCard: View {
    public let data: CohortRetentionData?
    public let isLoading: Bool

    public init(data: CohortRetentionData?, isLoading: Bool = false) {
        self.data = data
        self.isLoading = isLoading
    }

    private var maxOffset: Int {
        data?.cohorts.flatMap(\.cells).map(\.monthOffset).max() ?? 5
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: BrandSpacing.sm) {
            headerRow
            if isLoading {
                loadingPlaceholder
            } else if let d = data, !d.cohorts.isEmpty {
                cohortGrid(d)
                legend
            } else {
                emptyState
            }
        }
        .padding(BrandSpacing.base)
        .background(Color.bizarreSurface1,
                    in: RoundedRectangle(cornerRadius: DesignTokens.Radius.lg))
        .overlay(
            RoundedRectangle(cornerRadius: DesignTokens.Radius.lg)
                .strokeBorder(Color.bizarreOutline.opacity(0.4), lineWidth: 0.5)
        )
    }

    // MARK: - Sub-views

    private var headerRow: some View {
        HStack(spacing: BrandSpacing.xs) {
            Image(systemName: "chart.bar.xaxis.ascending")
                .foregroundStyle(.bizarreOrange)
                .accessibilityHidden(true)
            Text("Cohort Revenue Retention")
                .font(.brandTitleMedium())
                .foregroundStyle(.bizarreOnSurface)
                .accessibilityAddTraits(.isHeader)
            Spacer()
        }
    }

    private func cohortGrid(_ d: CohortRetentionData) -> some View {
        ScrollView([.horizontal, .vertical], showsIndicators: true) {
            VStack(alignment: .leading, spacing: 2) {
                // Column headers
                columnHeaders
                // Cohort rows
                ForEach(d.cohorts) { row in
                    cohortRowView(row)
                }
            }
        }
        .frame(maxHeight: min(400, CGFloat(d.cohorts.count + 1) * 40))
        .accessibilityLabel("Cohort retention heatmap with \(d.cohorts.count) cohorts")
    }

    private var columnHeaders: some View {
        HStack(spacing: 2) {
            Text("Cohort")
                .font(.brandLabelSmall())
                .foregroundStyle(.bizarreOnSurfaceMuted)
                .frame(width: 72, alignment: .leading)
            ForEach(0...maxOffset, id: \.self) { offset in
                Text(offset == 0 ? "M0" : "M+\(offset)")
                    .font(.brandLabelSmall())
                    .foregroundStyle(.bizarreOnSurfaceMuted)
                    .frame(width: 48, alignment: .center)
            }
        }
    }

    private func cohortRowView(_ row: CohortRow) -> some View {
        HStack(spacing: 2) {
            Text(row.cohortMonth)
                .font(.brandLabelSmall())
                .foregroundStyle(.bizarreOnSurface)
                .frame(width: 72, alignment: .leading)
                .lineLimit(1)
            ForEach(0...maxOffset, id: \.self) { offset in
                let cell = row.cells.first { $0.monthOffset == offset }
                cohortCell(cell, offset: offset)
            }
        }
    }

    private func cohortCell(_ cell: CohortCell?, offset: Int) -> some View {
        let pct = cell?.retentionPct ?? 0
        let opacity = pct > 0 ? max(0.15, min(1.0, pct / 100.0)) : 0.0
        let label = cell.map { c in
            String(format: "%.0f%%", c.retentionPct)
        } ?? "—"

        return ZStack {
            RoundedRectangle(cornerRadius: DesignTokens.Radius.xs)
                .fill(offset == 0 ? Color.bizarreOrange : Color.bizarreSuccess)
                .opacity(offset == 0 ? 0.8 : opacity)
            Text(label)
                .font(.brandLabelSmall())
                .foregroundStyle(pct > 50 ? .white : .bizarreOnSurface)
                .lineLimit(1)
                .minimumScaleFactor(0.7)
        }
        .frame(width: 48, height: 34)
        .accessibilityLabel(cell.map { c in
            "Month \(offset): \(String(format: "%.0f", c.retentionPct)) percent, $\(String(format: "%.0f", c.revenueDollars))"
        } ?? "Month \(offset): no data")
    }

    private var legend: some View {
        HStack(spacing: BrandSpacing.sm) {
            legendChip(color: .bizarreOrange, label: "Acquisition")
            legendChip(color: .bizarreSuccess, label: "Return visit")
            Spacer()
            Text("Color intensity = retention %")
                .font(.brandLabelSmall())
                .foregroundStyle(.bizarreOnSurfaceMuted)
        }
    }

    private func legendChip(color: Color, label: String) -> some View {
        HStack(spacing: BrandSpacing.xxs) {
            RoundedRectangle(cornerRadius: 3)
                .fill(color)
                .frame(width: 14, height: 14)
                .accessibilityHidden(true)
            Text(label)
                .font(.brandLabelSmall())
                .foregroundStyle(.bizarreOnSurfaceMuted)
        }
    }

    private var loadingPlaceholder: some View {
        VStack(spacing: BrandSpacing.sm) {
            ForEach(0..<4, id: \.self) { _ in
                RoundedRectangle(cornerRadius: DesignTokens.Radius.sm)
                    .fill(Color.bizarreSurface2)
                    .frame(height: 34)
                    .shimmer()
            }
        }
    }

    private var emptyState: some View {
        VStack(spacing: BrandSpacing.sm) {
            Image(systemName: "arrow.trianglehead.2.counterclockwise")
                .font(.system(size: 32))
                .foregroundStyle(.bizarreOnSurfaceMuted)
                .accessibilityHidden(true)
            Text("No cohort data available yet.")
                .font(.brandBodyMedium())
                .foregroundStyle(.bizarreOnSurfaceMuted)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, BrandSpacing.lg)
        .accessibilityLabel("No cohort retention data available")
    }
}
