import XCTest
@testable import Dashboard
import Networking

// MARK: - DashboardWideLayoutTests
//
// Tests for the helper functions exposed by DashboardWideLayout.swift:
//   • `attentionItemsForWide(from:)` — item count, label order, counts, icons
//
// No SwiftUI rendering. All tests are pure logic via @testable import.

final class DashboardWideLayoutTests: XCTestCase {

    // MARK: - attentionItemsForWide: item count

    func test_attentionItemsForWide_returnsExactly4Items() {
        let attention = NeedsAttention()
        let items = attentionItemsForWide(from: attention)
        XCTAssertEqual(items.count, 4)
    }

    // MARK: - attentionItemsForWide: label order

    func test_attentionItemsForWide_labelOrder_isStable() {
        let attention = NeedsAttention()
        let labels = attentionItemsForWide(from: attention).map(\.label)
        XCTAssertEqual(labels, [
            "Stale tickets",
            "Overdue invoices",
            "Missing parts",
            "Low stock",
        ])
    }

    // MARK: - attentionItemsForWide: counts

    func test_attentionItemsForWide_staleTickets_count() {
        let ticket = NeedsAttention.StaleTicket(
            id: 1, orderId: "T-001", customerName: "Alice", daysStale: 3, status: "Open"
        )
        let attention = NeedsAttention(staleTickets: [ticket, ticket])
        let item = attentionItemsForWide(from: attention).first { $0.label == "Stale tickets" }
        XCTAssertEqual(item?.count, 2)
    }

    func test_attentionItemsForWide_overdueInvoices_count() {
        let invoice = NeedsAttention.OverdueInvoice(
            id: 2, orderId: "I-001", customerName: "Bob", amountDue: 250.0, daysOverdue: 5
        )
        let attention = NeedsAttention(overdueInvoices: [invoice])
        let item = attentionItemsForWide(from: attention).first { $0.label == "Overdue invoices" }
        XCTAssertEqual(item?.count, 1)
    }

    func test_attentionItemsForWide_missingParts_count() {
        let attention = NeedsAttention(missingPartsCount: 7)
        let item = attentionItemsForWide(from: attention).first { $0.label == "Missing parts" }
        XCTAssertEqual(item?.count, 7)
    }

    func test_attentionItemsForWide_lowStock_count() {
        let attention = NeedsAttention(lowStockCount: 12)
        let item = attentionItemsForWide(from: attention).first { $0.label == "Low stock" }
        XCTAssertEqual(item?.count, 12)
    }

    // MARK: - attentionItemsForWide: all-zero counts

    func test_attentionItemsForWide_allZero_totalIsZero() {
        let attention = NeedsAttention()
        let items = attentionItemsForWide(from: attention)
        let total = items.reduce(0) { $0 + $1.count }
        XCTAssertEqual(total, 0)
    }

    func test_attentionItemsForWide_nonZeroItems_totalIsCorrect() {
        let attention = NeedsAttention(missingPartsCount: 3, lowStockCount: 5)
        let items = attentionItemsForWide(from: attention)
        let total = items.reduce(0) { $0 + $1.count }
        XCTAssertEqual(total, 8)
    }

    // MARK: - attentionItemsForWide: icons

    func test_attentionItemsForWide_allItemsHaveNonEmptyIcon() {
        let attention = NeedsAttention()
        let items = attentionItemsForWide(from: attention)
        for item in items {
            XCTAssertFalse(item.icon.isEmpty,
                "Item '\(item.label)' must have a non-empty SF Symbol icon name")
        }
    }

    func test_attentionItemsForWide_iconsAreDistinct() {
        // Each category should use a different icon for visual differentiation.
        let attention = NeedsAttention()
        let icons = attentionItemsForWide(from: attention).map(\.icon)
        let uniqueIcons = Set(icons)
        XCTAssertEqual(uniqueIcons.count, icons.count,
            "Each attention category must use a unique icon")
    }

    // MARK: - attentionItemsForWide: unique IDs

    func test_attentionItemsForWide_idsAreUnique() {
        let attention = NeedsAttention()
        let items = attentionItemsForWide(from: attention)
        let ids = Set(items.map(\.id))
        XCTAssertEqual(ids.count, items.count, "Each attention item must have a unique ID")
    }

    // MARK: - WideAttentionItem model

    func test_wideAttentionItem_init_storesValues() {
        let item = WideAttentionItem(label: "Test", count: 5, icon: "star")
        XCTAssertEqual(item.label, "Test")
        XCTAssertEqual(item.count, 5)
        XCTAssertEqual(item.icon, "star")
    }

    func test_wideAttentionItem_idIsAutoGenerated() {
        let a = WideAttentionItem(label: "Test", count: 0, icon: "star")
        let b = WideAttentionItem(label: "Test", count: 0, icon: "star")
        // IDs must differ even when all other properties match.
        XCTAssertNotEqual(a.id, b.id)
    }
}
