#!/usr/bin/env bash
# gen-pseudo-loc.sh — §27 pseudo-locale generator
#
# Reads  ios/App/Resources/Locales/en.lproj/Localizable.strings
# Writes ios/App/Resources/Locales/pseudo.lproj/Localizable.strings
#
# Transforms applied:
#   1. Accent substitution  a→â e→é i→î o→ô u→û (detects non-localised strings)
#   2. ~40% length padding  with middle-dots after the value content
#   3. Bracket wrapping     ⟦…⟧ (catches hardcoded strings that never expand)
#
# macOS-compatible: POSIX awk only.
#
# Usage:
#   bash ios/scripts/gen-pseudo-loc.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SRC="${REPO_ROOT}/App/Resources/Locales/en.lproj/Localizable.strings"
DST_DIR="${REPO_ROOT}/App/Resources/Locales/pseudo.lproj"
DST="${DST_DIR}/Localizable.strings"

if [[ ! -f "${SRC}" ]]; then
    echo "ERROR: source file not found: ${SRC}" >&2
    exit 1
fi

mkdir -p "${DST_DIR}"

python3 - "${SRC}" "${DST}" <<'PYEOF'
import sys, re

src_path = sys.argv[1]
dst_path = sys.argv[2]

ACCENT = str.maketrans("aeiouAEIOU", "âéîôûÂÉÎÔÛ")

def pseudo(val: str) -> str:
    accented = val.translate(ACCENT)
    pad_count = max(int(len(val) * 0.4), 3)
    return "\u27e6" + accented + "\u00b7" * pad_count + "\u27e7"

header = (
    "/* BizarreCRM — Pseudo-locale (pseudo) Localizable.strings\n"
    "   AUTO-GENERATED by ios/scripts/gen-pseudo-loc.sh — DO NOT EDIT BY HAND.\n"
    "   Re-run the script after updating en.lproj/Localizable.strings.\n"
    "\n"
    "   Purpose: validates:\n"
    "     - Text expansion (40% extra length) — catches UI truncation\n"
    "     - Accent decoration — reveals un-localised (hardcoded) English strings\n"
    "     - \u27e6bracket\u27e7 wrapping — catches strings never passing through NSLocalizedString\n"
    "*/\n"
)

pattern = re.compile(r'^("(?:[^"\\]|\\.)+") *= *"((?:[^"\\]|\\.)*)" *;')

out_lines = [header]
with open(src_path, encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        m = pattern.match(line)
        if m:
            key = m.group(1)
            val = m.group(2)
            out_lines.append(f'{key} = "{pseudo(val)}";')
        elif line.startswith("/*") or line.startswith("//") or line.strip() == "" or "MARK:" in line:
            out_lines.append(line)
        else:
            out_lines.append(line)

with open(dst_path, "w", encoding="utf-8") as f:
    f.write("\n".join(out_lines) + "\n")

count = sum(1 for l in out_lines if l.startswith('"'))
print(f"pseudo.lproj generated: {count} keys → {dst_path}")
PYEOF
