package com.bizarreelectronics.crm.util

import android.app.Activity
import android.net.Uri
import androidx.browser.customtabs.CustomTabsIntent
import timber.log.Timber

/**
 * §2.20 L444 — Chrome Custom Tabs wrapper for SSO / SAML / OIDC sign-in.
 *
 * Launches the IdP authorization URL in a Chrome Custom Tab so the browser
 * handles all cookies and session state. After the user authenticates, the
 * IdP redirects to:
 *
 *   bizarrecrm://sso/callback?code=<auth-code>&state=<csrf-state>
 *
 * That URI is intercepted by the `<intent-filter>` in AndroidManifest for the
 * `bizarrecrm` scheme / `sso` host, which delivers an [android.content.Intent]
 * to [com.bizarreelectronics.crm.MainActivity.onNewIntent]. MainActivity extracts
 * [code] + [state] from the query parameters and dispatches them via
 * [DeepLinkBus.publishSsoResult] for the ViewModel to process.
 *
 * SAML vs OIDC distinction: entirely handled server-side. The [authUrl] may be
 * an OIDC `/authorize` endpoint or a SAML SP-initiated SSO URL. Android sees only
 * the authorization redirect URL and the resulting `code` callback — the protocol
 * details are opaque to the client.
 *
 * L444 — Certificate rotation TODO: follow-up server task. When the IdP rotates
 * its signing certificate the server must re-fetch OIDC/SAML metadata. Android
 * is not involved in cert validation; future follow-up tracked server-side.
 *
 * @param activity The current foreground [Activity]; required by [CustomTabsIntent.launchUrl].
 * @param authUrl  The IdP authorization URL returned by GET /auth/sso/providers.
 * @param state    CSRF state token generated by the ViewModel; echoed back in the callback.
 */
object SsoLauncher {

    /**
     * Opens [authUrl] in a Chrome Custom Tab. The Custom Tab uses the app's
     * primary color scheme so the transition feels native. The IdP redirect
     * back to `bizarrecrm://sso/callback` will be picked up by the manifest
     * intent-filter on MainActivity.
     *
     * No-op if [authUrl] is blank (guards against bad server responses).
     */
    fun launch(activity: Activity, authUrl: String, @Suppress("UNUSED_PARAMETER") state: String) {
        if (authUrl.isBlank()) {
            Timber.w("SsoLauncher.launch: authUrl is blank — skipping")
            return
        }
        val customTabIntent = CustomTabsIntent.Builder()
            .setColorScheme(CustomTabsIntent.COLOR_SCHEME_SYSTEM)
            .setShowTitle(true)
            .build()

        Timber.d("SsoLauncher: launching SSO auth URL via Chrome Custom Tab")
        customTabIntent.launchUrl(activity, Uri.parse(authUrl))
    }
}
