@echo off
setlocal enabledelayedexpansion
title BizarreCRM Update
color 0B
set "ROOT=%~dp0.."
cd /d "%ROOT%"

echo.
echo  ======================================
echo    BizarreCRM — Updating...
echo  ======================================
echo.

:: Step 1: Pull latest code
echo  [1/5] Pulling latest code...
:: SAFETY: Only reset package-lock.json (auto-generated by npm install, NOT user data).
:: NEVER reset: .env, *.db, uploads/, certs/, data/ — those are protected by .gitignore
:: and will NEVER be touched by git pull.
git checkout -- package-lock.json 2>nul
git pull origin main
if %errorlevel% neq 0 (
    color 0C
    echo  ERROR: git pull failed.
    pause
    exit /b 1
)
echo  OK

:: Step 2: Kill everything (wait a moment so server can send response first)
echo.
echo  [2/5] Stopping server and dashboard...
timeout /t 3 /nobreak >nul
taskkill /F /IM "BizarreCRM Management.exe" 2>nul
taskkill /F /IM node.exe 2>nul
:: Wait for processes to fully exit
timeout /t 5 /nobreak >nul
echo  OK - Processes stopped

:: Step 3: Install deps + build
:: Use `npm ci` (not `npm install`) for deployments — it installs exactly what's
:: in package-lock.json WITHOUT regenerating it. This prevents the "local changes
:: would be overwritten by merge" conflict on the next git pull, because the
:: server never mutates the lockfile. Only use `npm install` when actually
:: adding/removing dependencies during development.
echo.
echo  [3/5] Installing dependencies (npm ci)...
call npm ci
echo.
echo  [4/5] Building everything...
call npm run build
if %errorlevel% neq 0 (
    color 0C
    echo  ERROR: Build failed.
    pause
    exit /b 1
)

:: Build + package dashboard
pushd packages\management
call npm run build
call npm run package 2>nul
if exist "release\win-unpacked" (
    if exist "%ROOT%\dashboard" rmdir /s /q "%ROOT%\dashboard" 2>nul
    xcopy /E /I /Q /Y "release\win-unpacked" "%ROOT%\dashboard" >nul 2>nul
    echo  OK - Dashboard rebuilt
)
popd

:: Step 5: Launch dashboard (which auto-starts server)
echo.
echo  [5/5] Launching dashboard...

set "DASHBOARD="
if exist "%ROOT%\dashboard\BizarreCRM Management.exe" set "DASHBOARD=%ROOT%\dashboard\BizarreCRM Management.exe"
if not defined DASHBOARD if exist "%ROOT%\packages\management\release\win-unpacked\BizarreCRM Management.exe" set "DASHBOARD=%ROOT%\packages\management\release\win-unpacked\BizarreCRM Management.exe"

if defined DASHBOARD (
    start "" "!DASHBOARD!"
) else (
    echo  Dashboard EXE not found. Starting server directly...
    start "BizarreCRM Server" cmd /k "cd /d "%ROOT%\packages\server" && npx tsx src/index.ts"
)

color 0A
echo.
echo  ======================================
echo    Update Complete!
echo  ======================================
echo.
echo  Press any key to close this window.
pause
