#if canImport(UIKit)
import SwiftUI
import Core
import DesignSystem

// MARK: - FinancingProvider

/// §16.6 — Supported BNPL / financing partners.
/// The tenant enables one or more via `GET /settings/financing`.
public enum FinancingProvider: String, CaseIterable, Sendable, Codable, Hashable {
    case affirm  = "affirm"
    case klarna  = "klarna"

    public var displayName: String {
        switch self {
        case .affirm: return "Affirm"
        case .klarna: return "Klarna"
        }
    }

    public var systemImage: String {
        switch self {
        case .affirm: return "creditcard.trianglebadge.exclamationmark"
        case .klarna: return "k.square.fill"
        }
    }

    public var tagline: String {
        switch self {
        case .affirm: return "Split into 3–36 monthly payments"
        case .klarna: return "Buy now, pay later in 4 installments"
        }
    }
}

// MARK: - PosFinancingLinkSheet

/// §16.6 — Financing (Affirm / Klarna) tender sheet.
///
/// When financing is enabled the cashier taps the "Financing" tile in the
/// tender picker, selects the provider, and receives a deep-link URL.
/// The customer completes checkout on their phone; a server webhook fires
/// `POST /invoices/:id/payments` when the partner approves, completing the sale.
///
/// iOS side: generate + share the URL via `UIActivityViewController`.
/// The sheet polls `GET /invoices/:id` every 5s until payment_status changes
/// from `pending` to `paid` (or until the cashier cancels).
///
/// Sovereignty: no partner SDK is imported. We use server-generated redirect
/// URLs only — the partner's web flow handles all sensitive data.
@MainActor
public struct PosFinancingLinkSheet: View {

    // MARK: - Inputs

    public let dueCents: Int
    public let providers: [FinancingProvider]
    /// Server-generated checkout URL template. Replace `{provider}` with the
    /// selected provider slug. Generated by `GET /pos/financing-url?amount=N`.
    public let checkoutURL: URL?
    public let onCancel: () -> Void

    // MARK: - State

    @State private var selectedProvider: FinancingProvider?
    @State private var isPolling: Bool = false
    @State private var showShareSheet: Bool = false
    @State private var providerURL: URL?
    @State private var pollTask: Task<Void, Never>?

    @Environment(\.posTheme) private var theme

    public init(
        dueCents: Int,
        providers: [FinancingProvider] = FinancingProvider.allCases,
        checkoutURL: URL? = nil,
        onCancel: @escaping () -> Void
    ) {
        self.dueCents = dueCents
        self.providers = providers
        self.checkoutURL = checkoutURL
        self.onCancel = onCancel
    }

    // MARK: - Body

    public var body: some View {
        VStack(spacing: 0) {
            // Header
            VStack(spacing: BrandSpacing.xxs) {
                Image(systemName: "arrow.triangle.branch")
                    .font(.system(size: 32, weight: .medium))
                    .foregroundStyle(theme.primary)
                    .padding(.top, BrandSpacing.xl)
                    .accessibilityHidden(true)
                Text("Financing")
                    .font(.brandTitleLarge())
                    .foregroundStyle(theme.on)
                Text(CartMath.formatCents(dueCents))
                    .font(.brandDisplayMedium())
                    .foregroundStyle(theme.on)
                    .monospacedDigit()
                    .dynamicTypeSize(...DynamicTypeSize.accessibility2)
                Text("Customer completes checkout on their phone")
                    .font(.brandLabelSmall())
                    .foregroundStyle(theme.muted)
                    .multilineTextAlignment(.center)
                    .padding(.top, BrandSpacing.xxs)
            }
            .padding(.bottom, BrandSpacing.lg)

            ScrollView {
                VStack(spacing: BrandSpacing.md) {

                    Text("SELECT PROVIDER")
                        .font(.brandLabelSmall())
                        .foregroundStyle(theme.muted)
                        .textCase(.uppercase)
                        .kerning(0.8)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal, BrandSpacing.sm)

                    ForEach(providers, id: \.self) { provider in
                        providerTile(provider)
                    }

                    if isPolling {
                        pollingBanner
                    }

                    // Instructions
                    VStack(alignment: .leading, spacing: BrandSpacing.xs) {
                        Label("Share the link with the customer via SMS or QR", systemImage: "square.and.arrow.up")
                        Label("Customer completes financing on their device", systemImage: "iphone")
                        Label("Sale completes automatically when approved", systemImage: "checkmark.circle")
                    }
                    .font(.brandBodySmall())
                    .foregroundStyle(theme.muted)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(BrandSpacing.md)
                    .background(theme.surfaceElev, in: RoundedRectangle(cornerRadius: 12))
                }
                .padding(.horizontal, BrandSpacing.base)
                .padding(.bottom, BrandSpacing.lg)
            }

            Divider()
            HStack(spacing: BrandSpacing.sm) {
                Button("Cancel") {
                    pollTask?.cancel()
                    onCancel()
                }
                .buttonStyle(.bordered)
                .tint(.secondary)
                .frame(maxWidth: .infinity)
                .controlSize(.large)
                .accessibilityIdentifier("pos.financing.cancel")

                Button {
                    guard let provider = selectedProvider,
                          let base = checkoutURL else { return }
                    let url = URL(string: base.absoluteString.replacingOccurrences(of: "{provider}", with: provider.rawValue))
                    providerURL = url
                    showShareSheet = true
                    isPolling = true
                } label: {
                    Label("Send link", systemImage: "square.and.arrow.up")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .tint(theme.primary)
                .disabled(selectedProvider == nil || checkoutURL == nil)
                .controlSize(.large)
                .accessibilityIdentifier("pos.financing.sendLink")
            }
            .padding(.horizontal, BrandSpacing.base)
            .padding(.vertical, BrandSpacing.md)
            .background(theme.bg)
        }
        .background(theme.bg.ignoresSafeArea())
        .sheet(isPresented: $showShareSheet) {
            if let url = providerURL {
                ShareSheet(activityItems: [url])
            }
        }
    }

    // MARK: - Sub-views

    private func providerTile(_ provider: FinancingProvider) -> some View {
        Button {
            selectedProvider = provider
            BrandHaptics.selection()
        } label: {
            HStack(spacing: BrandSpacing.md) {
                Image(systemName: provider.systemImage)
                    .font(.system(size: 24, weight: .medium))
                    .foregroundStyle(selectedProvider == provider ? theme.primary : theme.muted)
                    .frame(width: 32)
                    .accessibilityHidden(true)
                VStack(alignment: .leading, spacing: BrandSpacing.xxs) {
                    Text(provider.displayName)
                        .font(.brandBodyLarge())
                        .foregroundStyle(theme.on)
                    Text(provider.tagline)
                        .font(.brandBodySmall())
                        .foregroundStyle(theme.muted)
                }
                Spacer()
                if selectedProvider == provider {
                    Image(systemName: "checkmark.circle.fill")
                        .foregroundStyle(theme.primary)
                        .accessibilityHidden(true)
                }
            }
            .padding(BrandSpacing.md)
            .background(
                RoundedRectangle(cornerRadius: 12)
                    .fill(selectedProvider == provider
                          ? theme.primary.opacity(0.08)
                          : theme.surfaceElev)
            )
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .strokeBorder(
                        selectedProvider == provider ? theme.primary : theme.outline,
                        lineWidth: selectedProvider == provider ? 1.5 : 1
                    )
            )
        }
        .buttonStyle(.plain)
        .accessibilityLabel("\(provider.displayName): \(provider.tagline)")
        .accessibilityAddTraits(selectedProvider == provider ? .isSelected : [])
        .accessibilityIdentifier("pos.financing.provider.\(provider.rawValue)")
    }

    private var pollingBanner: some View {
        HStack(spacing: BrandSpacing.sm) {
            ProgressView()
                .tint(theme.primary)
                .accessibilityHidden(true)
            Text("Waiting for customer to complete financing…")
                .font(.brandBodyMedium())
                .foregroundStyle(theme.on)
        }
        .padding(BrandSpacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(theme.surfaceElev, in: RoundedRectangle(cornerRadius: 12))
        .accessibilityLabel("Waiting for customer to complete financing checkout")
    }
}

// MARK: - ShareSheet (UIKit bridge)

/// Minimal `UIActivityViewController` wrapper for SwiftUI.
/// Uses only iOS-native share; no third-party SDK.
private struct ShareSheet: UIViewControllerRepresentable {
    let activityItems: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: activityItems, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}

// MARK: - Preview

#Preview("Financing sheet") {
    PosFinancingLinkSheet(
        dueCents: 89900,
        providers: FinancingProvider.allCases,
        checkoutURL: URL(string: "https://app.bizarrecrm.com/pay/financing?amount=89900&provider={provider}"),
        onCancel: { print("Cancelled") }
    )
    .preferredColorScheme(.dark)
}
#endif
