/**
 * Generate .env file with cryptographically random secrets.
 * Skips if .env already exists (won't overwrite).
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const envPath = path.resolve(__dirname, '../../../.env');

if (fs.existsSync(envPath)) {
  console.log('[setup] .env already exists — skipping');
  process.exit(0);
}

const domain = (process.argv[2] || 'localhost').trim().toLowerCase();
const jwtSecret = crypto.randomBytes(64).toString('hex');
const jwtRefreshSecret = crypto.randomBytes(64).toString('hex');
const superAdminSecret = crypto.randomBytes(32).toString('hex');

const envContent = `# BizarreCRM Server Configuration
# Generated by setup script on ${new Date().toISOString().slice(0, 10)}

PORT=443
HOST=0.0.0.0
NODE_ENV=production

# Auth secrets (auto-generated, unique to this install)
JWT_SECRET=${jwtSecret}
JWT_REFRESH_SECRET=${jwtRefreshSecret}
SUPER_ADMIN_SECRET=${superAdminSecret}

# Multi-tenant mode (subdomain-based tenant routing)
MULTI_TENANT=true
BASE_DOMAIN=${domain}
`;

fs.writeFileSync(envPath, envContent, 'utf-8');
console.log(`[setup] .env created (domain: ${domain})`);
