/**
 * Generate or upgrade the .env file.
 *
 * Two modes:
 *   1. FRESH INSTALL (no .env exists) — writes the full template with a
 *      random JWT secret set, multi-tenant defaults, and empty placeholders
 *      for optional features (Cloudflare DNS).
 *
 *   2. UPGRADE (.env already exists) — scans the existing file for each
 *      known section and APPENDS any missing ones to the end. Never modifies
 *      or regenerates values that are already present. This is how new env
 *      vars introduced after the initial install reach a running server —
 *      because `.env` is gitignored, `git pull` cannot deliver them.
 *
 * Safe to re-run any number of times. Nothing is ever deleted or overwritten.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const envPath = path.resolve(__dirname, '../../../.env');
const domain = (process.argv[2] || 'localhost').trim().toLowerCase();

// Each section has:
//   name:     short label for log output
//   detector: regex that matches if the section is already present in .env
//   block():  returns the text to append (called only if missing)
// Sections are appended in this order on fresh install. On upgrade, only the
// missing ones are appended, at the end of the file, under a dated separator.
const SECTIONS = [
  {
    name: 'server',
    detector: /^PORT=/m,
    block: () => `PORT=443
HOST=0.0.0.0
NODE_ENV=production

`,
  },
  {
    name: 'auth',
    detector: /^JWT_SECRET=/m,
    block: () => {
      const jwtSecret = crypto.randomBytes(64).toString('hex');
      const jwtRefreshSecret = crypto.randomBytes(64).toString('hex');
      const superAdminSecret = crypto.randomBytes(32).toString('hex');
      return `# Auth secrets (auto-generated, unique to this install)
JWT_SECRET=${jwtSecret}
JWT_REFRESH_SECRET=${jwtRefreshSecret}
SUPER_ADMIN_SECRET=${superAdminSecret}

`;
    },
  },
  {
    // SEC-H54: signed-URL HMAC secret for /uploads + portal/MMS public
    // links. config.ts FATAL-exits in production if this is missing or
    // shorter than 32 chars, so a fresh install without this section
    // would pm2 restart-loop forever. Domain-separated from JWT_SECRET
    // deliberately — if a JWT leak happens, signed-URL minting must not
    // also fall to the attacker.
    name: 'uploads',
    detector: /^UPLOADS_SECRET=/m,
    block: () => {
      const uploadsSecret = crypto.randomBytes(32).toString('hex');
      return `# Signed-URL HMAC secret for /uploads + portal/MMS public links (SEC-H54)
UPLOADS_SECRET=${uploadsSecret}

`;
    },
  },
  {
    // PROD54 / SEC-M49: backup encryption key. backup.ts throws in
    // production when absent. Separate from JWT_SECRET so an auth leak
    // doesn't also decrypt every stored backup.
    name: 'backup',
    detector: /^BACKUP_ENCRYPTION_KEY=/m,
    block: () => {
      const backupKey = crypto.randomBytes(32).toString('hex');
      return `# Backup encryption key — AES-256-GCM over each .db.enc file (PROD54)
BACKUP_ENCRYPTION_KEY=${backupKey}

`;
    },
  },
  {
    name: 'multi-tenant',
    detector: /^MULTI_TENANT=/m,
    block: () => `# Multi-tenant mode (subdomain-based tenant routing)
MULTI_TENANT=true
BASE_DOMAIN=${domain}

`,
  },
  {
    name: 'cloudflare',
    // Detect on the token line; zone id / public ip are grouped with it.
    detector: /^CLOUDFLARE_API_TOKEN=/m,
    block: () => `# Cloudflare DNS auto-provisioning — REQUIRED for tenant subdomain auto-creation
# in multi-tenant mode. Without these three values, new shop signups succeed in
# the master DB but no DNS record is created, so shop subdomains return
# "Server Not Found" in the browser.
#
# Setup:
#   1. Cloudflare dashboard > My Profile > API Tokens > Create Token > Custom token
#      Permissions: Zone > DNS > Edit
#      Zone Resources: Include > Specific zone > your domain
#   2. Find Zone ID: Cloudflare dashboard > your domain > right sidebar > Zone ID
#   3. SERVER_PUBLIC_IP is the same IP your apex A record points to.
#
# Leave empty to disable auto-DNS (you'll need to manage DNS manually via a
# wildcard record — see README.md Self-Hosting section).
CLOUDFLARE_API_TOKEN=
CLOUDFLARE_ZONE_ID=
SERVER_PUBLIC_IP=

`,
  },
];

const HEADER = `# BizarreCRM Server Configuration
# Generated by setup script on ${new Date().toISOString().slice(0, 10)}

`;

function freshInstall() {
  const envContent = HEADER + SECTIONS.map((s) => s.block()).join('');
  fs.writeFileSync(envPath, envContent, 'utf-8');
  console.log(`[setup] .env created (domain: ${domain})`);
  console.log('[setup] Cloudflare auto-DNS is disabled until you fill in CLOUDFLARE_API_TOKEN,');
  console.log('[setup] CLOUDFLARE_ZONE_ID, and SERVER_PUBLIC_IP in .env — see the section in the file.');
}

function upgradeExisting() {
  const existing = fs.readFileSync(envPath, 'utf-8');
  const missing = SECTIONS.filter((s) => !s.detector.test(existing));

  if (missing.length === 0) {
    console.log('[setup] .env is up to date');
    return;
  }

  // Make sure the existing file ends with a newline so the separator is on its own line.
  let updated = existing.endsWith('\n') ? existing : existing + '\n';
  updated += `\n# ── Added by setup script on ${new Date().toISOString().slice(0, 10)} (new sections since your install) ──\n\n`;
  for (const section of missing) {
    updated += section.block();
  }

  fs.writeFileSync(envPath, updated, 'utf-8');
  console.log(`[setup] .env upgraded — appended missing sections: ${missing.map((s) => s.name).join(', ')}`);
  if (missing.some((s) => s.name === 'cloudflare')) {
    console.log('[setup] ACTION NEEDED: open .env and fill in CLOUDFLARE_API_TOKEN,');
    console.log('[setup] CLOUDFLARE_ZONE_ID, and SERVER_PUBLIC_IP, then restart the server.');
  }
}

if (fs.existsSync(envPath)) {
  upgradeExisting();
} else {
  freshInstall();
}
